### ISSUE TITLE
double free or corruption (fasttop)

### ISSUE THREAD

**Issue by Grimy** [Palamecia/mint#1]
How to reproduce
==============

After building 7d85d10, run

    seq 2 | build/bin/mint

The interpreter outputs:

   1 >>> 1
 [00000000] PUSH 1
 [00000002] PRINT
 [00000003] END
 1
   2 >>> 2
 [00000004] PUSH 2
 [00000006] PRINT
 [00000007] END
 2
   3 >>>

This is mostly as expected (though the prompt probably shouldn’t be shown if stdin isn’t a tty). It then crashes with the following output:

    /usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7f53a3bd2291]
    build/bin/mint(_start+0x2a)[0x40081a]
    ======= Memory map: ========
    00400000-00401000 r-xp 00000000 00:13 24841765                           /home/grimy/src/mint/build/bin/mint
    00600000-00601000 r--p 00000000 00:13 24841765                           /home/grimy/src/mint/build/bin/mint
    00601000-00602000 rw-p 00001000 00:13 24841765                           /home/grimy/src/mint/build/bin/mint
    01102000-01176000 rw-p 00000000 00:00 0                                  [heap]
    7f539c000000-7f539c021000 rw-p 00000000 00:00 0
    7f539c021000-7f53a0000000 ---p 00000000 00:00 0
    7f53a3946000-7f53a39ad000 r-xp 00000000 00:13 22971239                   /usr/lib/libncursesw.so.6.0
    7f53a39ad000-7f53a3bac000 ---p 00067000 00:13 22971239                   /usr/lib/libncursesw.so.6.0
    7f53a3bac000-7f53a3bb0000 r--p 00066000 00:13 22971239                   /usr/lib/libncursesw.so.6.0
    7f53a3bb0000-7f53a3bb2000 rw-p 0006a000 00:13 22971239                   /usr/lib/libncursesw.so.6.0
    7f53a3bb2000-7f53a3d47000 r-xp 00000000 00:13 21579661                   /usr/lib/libc-2.24.so
    7f53a3d47000-7f53a3f46000 ---p 00195000 00:13 21579661                   /usr/lib/libc-2.24.so
    7f53a3f46000-7f53a3f4a000 r--p 00194000 00:13 21579661                   /usr/lib/libc-2.24.so
    7f53a3f4a000-7f53a3f4c000 rw-p 00198000 00:13 21579661                   /usr/lib/libc-2.24.so
    7f53a3f4c000-7f53a3f50000 rw-p 00000000 00:00 0
    7f53a3f50000-7f53a3f66000 r-xp 00000000 00:13 22971158                   /usr/lib/libgcc_s.so.1
    7f53a3f66000-7f53a4165000 ---p 00016000 00:13 22971158                   /usr/lib/libgcc_s.so.1
    7f53a4165000-7f53a4166000 r--p 00015000 00:13 22971158                   /usr/lib/libgcc_s.so.1
    7f53a4166000-7f53a4167000 rw-p 00016000 00:13 22971158                   /usr/lib/libgcc_s.so.1
    7f53a4167000-7f53a426a000 r-xp 00000000 00:13 21579715                   /usr/lib/libm-2.24.so
    7f53a426a000-7f53a4469000 ---p 00103000 00:13 21579715                   /usr/lib/libm-2.24.so
    7f53a4469000-7f53a446a000 r--p 00102000 00:13 21579715                   /usr/lib/libm-2.24.so
    7f53a446a000-7f53a446b000 rw-p 00103000 00:13 21579715                   /usr/lib/libm-2.24.so
    7f53a446b000-7f53a45e3000 r-xp 00000000 00:13 22971191                   /usr/lib/libstdc++.so.6.0.22
    7f53a45e3000-7f53a47e3000 ---p 00178000 00:13 22971191                   /usr/lib/libstdc++.so.6.0.22
    7f53a47e3000-7f53a47ed000 r--p 00178000 00:13 22971191                   /usr/lib/libstdc++.so.6.0.22
    7f53a47ed000-7f53a47ef000 rw-p 00182000 00:13 22971191                   /usr/lib/libstdc++.so.6.0.22
    7f53a47ef000-7f53a47f3000 rw-p 00000000 00:00 0
    7f53a47f3000-7f53a4837000 r-xp 00000000 00:13 22973871                   /usr/lib/libreadline.so.7.0
    7f53a4837000-7f53a4a37000 ---p 00044000 00:13 22973871                   /usr/lib/libreadline.so.7.0
    7f53a4a37000-7f53a4a39000 r--p 00044000 00:13 22973871                   /usr/lib/libreadline.so.7.0
    7f53a4a39000-7f53a4a3f000 rw-p 00046000 00:13 22973871                   /usr/lib/libreadline.so.7.0
    7f53a4a3f000-7f53a4a41000 rw-p 00000000 00:00 0
    7f53a4a41000-7f53a4a43000 r-xp 00000000 00:13 21579714                   /usr/lib/libdl-2.24.so
    7f53a4a43000-7f53a4c43000 ---p 00002000 00:13 21579714                   /usr/lib/libdl-2.24.so
    7f53a4c43000-7f53a4c44000 r--p 00002000 00:13 21579714                   /usr/lib/libdl-2.24.so
    7f53a4c44000-7f53a4c45000 rw-p 00003000 00:13 21579714                   /usr/lib/libdl-2.24.so
    7f53a4c45000-7f53a4d93000 r-xp 00000000 00:13 24841754                   /home/grimy/src/mint/build/lib/libmint.so
    7f53a4d93000-7f53a4f93000 ---p 0014e000 00:13 24841754                   /home/grimy/src/mint/build/lib/libmint.so
    7f53a4f93000-7f53a4f94000 r--p 0014e000 00:13 24841754                   /home/grimy/src/mint/build/lib/libmint.so
    7f53a4f94000-7f53a4f9c000 rw-p 0014f000 00:13 24841754                   /home/grimy/src/mint/build/lib/libmint.so
    7f53a4f9c000-7f53a4f9d000 rw-p 00000000 00:00 0
    7f53a4f9d000-7f53a4fc0000 r-xp 00000000 00:13 21579660                   /usr/lib/ld-2.24.so
    7f53a4fea000-7f53a5183000 r--p 00000000 00:13 21579983                   /usr/lib/locale/locale-archive
    7f53a5183000-7f53a5188000 rw-p 00000000 00:00 0
    7f53a51bc000-7f53a51bf000 rw-p 00000000 00:00 0
    7f53a51bf000-7f53a51c0000 r--p 00022000 00:13 21579660                   /usr/lib/ld-2.24.so
    7f53a51c0000-7f53a51c1000 rw-p 00023000 00:13 21579660                   /usr/lib/ld-2.24.so
    7f53a51c1000-7f53a51c2000 rw-p 00000000 00:00 0
    7ffcd029c000-7ffcd02bd000 rw-p 00000000 00:00 0                          [stack]
    7ffcd035f000-7ffcd0361000 r--p 00000000 00:00 0                          [vvar]
    7ffcd0361000-7ffcd0363000 r-xp 00000000 00:00 0                          [vdso]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by Palamecia** [comment]
This is fixed by 3a9778e.
