### ISSUE TITLE
Crash (floating point exception) on modulo 0

### ISSUE THREAD

**Issue by Grimy** [Palamecia/mint#3]
How to reproduce
-----------------------

Run the following Mint program:

    1%0

Expected results
---------------------

The interpreter cleanly reports a division by zero error.

Actual results
-----------------

The interpreter dumps core with the following output:

      1 >>> 1%0
    [00000000] PUSH 1
    [00000002] PUSH 0
    [00000004] MOD
    [00000005] PRINT
    [00000006] END
    floating point exception (core dumped)  bin/mint

**Comment by Palamecia** [comment]
Fixed by 7b8672d.
